/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Action: typeof import('./src/components/Action.vue')['default']
    Buttons: typeof import('./src/components/Buttons.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Copyright: typeof import('./src/components/Copyright.vue')['default']
    ElButotn: typeof import('element-plus/es')['ElButotn']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptions: typeof import('element-plus/es')['ElOptions']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Frame: typeof import('./src/components/Frame.vue')['default']
    FrameSizeSet: typeof import('./src/components/FrameSizeSet.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoItem: typeof import('./src/components/VideoItem.vue')['default']
    VideoList: typeof import('./src/components/VideoList.vue')['default']
  }
}
